name: build-image

on:
  push:
    branches-ignore: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kdwilson/pushshift-api:latest
